"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robot.gltf 
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Model = React.memo((props: any) => {
  const { nodes, materials } = useGLTF("/robot.gltf");

  const modelRef = useRef<any>();

  useFrame((state) => {
    modelRef.current.position.z =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
    </group>
  );
});
export default Model;

useGLTF.preload("/robot.gltf");
