/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robot.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
    </group>
  )
}

useGLTF.preload('/robot.gltf')
